server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://100.24.36.58:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://100.24.36.58:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://100.24.36.58:1003
    cart:
      path: /cart/**
      url: http://100.24.36.58:1004/api/v1
